### ISSUE TITLE
Calendar empty on Linux

### ISSUE THREAD

**Issue by Axel-Erfurt** [IntelligentVisibility/CalendarTimeChooser#14]
In 3_Cal-Time Chooser Custom Classes (Calendar Paint Event)

Targets are only Win and OSX

replace all lines
#ELSEIF TargetMacOS then
with
#ELSEIF TargetMacOS or TargetLinux then

**Comment by IntelligentVisibility** [comment]
Thank you Axel. I replaced all #IF TargetMacOS Then with  #IF TargetMacOS OR TargetLinux Then
