### ISSUE TITLE
24h mode property not ok?

### ISSUE THREAD

**Issue by PsychoAndi** [IntelligentVisibility/CalendarTimeChooser#22]
This is the way I'm  calling the Picker:

`MyPicker.drawColSeperatorLines = True`
`MyPicker.LocalizationInt = 6`
`MyPicker.StartYear =  DateTime.Now.Year - 3`
`MyPicker.EndYear = DateTime.Now.Year + 3`
`MyPicker.SelectedDate = DateTime.Now`
`MyPicker.TimeMode = 24`
`MyPicker.flashSeparator = False`
`MyPicker.Invalidate(False)`
`MyPicker.Show`

and when I try to read the selected date/time (in the DateTimeWindow code, where I created a button with an action event) with:
`ProgramWindow.chosenDate = self.SelectedDate`
`System.DebugLog("Datum = " + ProgramWindow.chosenDate.ToString(Locale.Current, DateTime.FormatStyles.Medium, DateTime.FormatStyles.Short))`

I get the following:
`Datum = 01.02.2020, 04:16`

When I change the MyPicker.TimeMode to 12 it's:
`Datum = 01.02.2020, 16:16`

The picker itself displays the 24hour-mode correctly, but the property `.SelectedDate` does not.

**Comment by IntelligentVisibility** [comment]
When I started this project I didn't really pay attention to people switching live in code from 12 to 24 --> I only added this on the UI demo as a courtesy for demoing only. It is undefined on how the behavior works from converting 12 <--> 24 in code. 

Is this of value for you in your software? I can add this feature properly if so.

**Comment by PsychoAndi** [comment]
I try to make an application that is used in the US and Germany at the same time. For now I have my own conversation of the time formats, but it'll be shorter and cleaner to have this directly from the chooser...

**Comment by IntelligentVisibility** [comment]
Thanks for the feedback - I will start a sprint to add/fix this behavior.

**Comment by npalardy** [comment]
Dates, and DateTimes, dont have a notion of the "representation"
That is a function of how the data in the date instance is formatted

**Comment by npalardy** [comment]
Something like the following will format the date using a german locale (one that uses 24 hr form in writing)
Note that if you want the date in one form and the time in another then a single locale may not suffice

```
Dim local As Locale = Locale.Current
Dim german As New Locale("de")

Dim currentTime As dateTime = DateTime.Now

Dim localTimeStr As String = currentTime.ToString( local, DateTime.FormatStyles.Medium, DateTime.FormatStyles.Short )
Dim germanTimeStr As String = currentTime.ToString( german, DateTime.FormatStyles.Medium, DateTime.FormatStyles.Short )

Break
```
